name: Deployment

  on:
    push:
      branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
  
    steps:
      name: Checkout code
      uses: actions/checkout@v2

      name: Setup Golang
      uses: actions/setup-go@v2

      name: Build app Go
      run: ./scripts/buildprod.sh